# Generated by Django 4.2.1 on 2023-05-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cuerpo',
            field=models.CharField(default=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
